spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: prjsoldoamanhecer@gmail.com
    password: qvlp jybj ijvl epbs
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
    default-encoding: UTF-8

cors:
  originPatterns: "http://localhost:8080, http://localhost:5173, http://213.136.68.204:8081, http://213.136.68.204:8083, http://api-homol.soldoamanhecer.com.br, http://api-prod.soldoamanhecer.com.br, https://213.136.68.204:8081, https://213.136.68.204:8083, https://api-homol.soldoamanhecer.com.br, https://api-prod.soldoamanhecer.com.br, http://hom.soldoamanhecer.com.br, http://soldoamanhecer.com.br, https://hom.soldoamanhecer.com.br, https://soldoamanhecer.com.br"


security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

springdoc:
  paths-to-match: /sol-do-amanhecer/api/**
  swagger-ui:
    use-root-path: true

management:
  endpoints:
    web:
      base-path: /sol-do-amanhecer/api/actuator