# CORS (ajuste conforme necessário em cada ambiente se preferir)
cors:
  originPatterns: "http://localhost:8080, http://localhost:8081, http://localhost:8082, http://localhost:4200"

# JWT
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

springdoc:
  paths-to-match: /sol-do-amanhecer/api/**
  swagger-ui:
    use-root-path: true

management:
  endpoints:
    web:
      base-path: /sol-do-amanhecer/api/actuator