spring:
  application:
    name: sol-do-amanhecer-api

  datasource:
    url: jdbc:postgresql://postgres-service:5432/soldoamanhecer?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
