name: Deploy API (Homologação)

on:
    push:
        branches:
            - homol

jobs:
    deploy-homolog:
        name: Deploy em Homologação
        runs-on: ubuntu-latest
        environment: homologacao

        steps:
            - name: Configurar chave SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
            
            - name: Gerar arquivo .env localmente
              run: |
                  cat > .env <<EOF
                    SPRING_PROFILES_ACTIVE=${{ secrets.SPRING_PROFILES_ACTIVE }}
                    APP_PORT=${{ secrets.APP_PORT }}
                    POSTGRES_HOST_PORT=${{ secrets.POSTGRES_HOST_PORT }}
                    POSTGRES_PORT=${{ secrets.POSTGRES_HOST_PORT }}
                    POSTGRES_DB=${{ secrets.POSTGRES_DB }}
                    POSTGRES_USER=${{ secrets.POSTGRES_USER }}
                    POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
                    APP_HOST_PORT=${{ secrets.APP_HOST_PORT }}
                  EOF
            - name: Enviar .env para VPS
              run: |
                  scp -i ~/.ssh/id_rsa .env ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_BACKEND_PATH }}/.env
            - name: Deploy na VPS (Homologação)
              env:
                  SPRING_PROFILES_ACTIVE: ${{ secrets.SPRING_PROFILES_ACTIVE }}
                  APP_PORT: ${{ secrets.APP_PORT }}
                  POSTGRES_HOST_PORT: ${{ secrets.POSTGRES_HOST_PORT }}
                  POSTGRES_PORT: ${{ secrets.POSTGRES_HOST_PORT }}
                  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
                  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                  APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
                  COMPOSE_PROJECT_NAME: api-homolog

              run: |
                  ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
                    set -e
                    cd ${{ secrets.VPS_BACKEND_PATH }}
                    
                    echo "=> Atualizando código da branch HOMOLOG..."
                    git pull origin homol
                     
                    echo "=> Forçando a reconstrução da imagem sem cache..."
                    docker compose --env-file .env.homol -p ${{ env.COMPOSE_PROJECT_NAME }} build --no-cache
                    echo "=> Forçando a recriação do container com a nova imagem..."
                    docker compose --env-file .env.homol -p ${{ env.COMPOSE_PROJECT_NAME }} up -d --force-recreate
                    echo "=> Limpando arquivo .env temporário..."
                    echo "mv .env.homol"
                  EOF
