name: Deploy API (Homologação)

on:
    push:
        branches:
            - homol

jobs:
    deploy-homolog:
        name: Deploy em Homologação
        runs-on: ubuntu-latest
        environment: homologacao

        steps:
            - name: Configurar chave SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

            - name: Deploy na VPS (Homologação)
              env:
                  SPRING_PROFILES_ACTIVE: ${{ secrets.SPRING_PROFILES_ACTIVE }}
                  APP_PORT: ${{ secrets.APP_PORT }}
                  POSTGRES_HOST_PORT: ${{ secrets.POSTGRES_HOST_PORT }}
                  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
                  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
                  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                  APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
                  COMPOSE_PROJECT_NAME: api-homolog

              run: |
                  ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
                    # O caminho vem do secret VPS_BACKEND_PATH que deve estar configurado no ambiente
                    cd ${{ secrets.VPS_BACKEND_PATH }}
                    
                    echo "=> Atualizando código da branch HOMOLOG..."
                    git fetch origin
                    git reset --hard origin/homol
                    
                    echo "=> Subindo ambiente de HOMOLOGAÇÃO..."
                    docker compose up -d --build
                  EOF
